image: ubuntu/bionic
sources:
  - https://github.com/xeffyr/termux-musl
packages:
  - build-essential
  - asciidoc
  - asciidoctor
  - autoconf
  - automake
  - bison
  - curl
  - ed
  - flex
  - g++-multilib
  - gawk
  - gettext
  - git
  - gnome-common
  - gtk-3-examples
  - gtk-doc-tools
  - gperf
  - help2man
  - intltool
  - libexpat1-dev
  - libgdk-pixbuf2.0-dev
  - libgmp-dev
  - libgtk-3-bin
  - libglib2.0-dev
  - libisl-dev
  - libjpeg-dev
  - libmpc-dev
  - libmpfr-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libssl-dev
  - libtool-bin
  - lzip
  - m4
  - openjdk-8-jdk-headless
  - pax-utils
  - pkg-config
  - python-pip
  - python3.7
  - python3-docutils
  - python3-pip
  - python3-setuptools
  - python3-sphinx
  - ruby
  - scons
  - texinfo
  - unzip
  - xfonts-utils
  - xmlto
  - zip
  - zlib1g-dev
tasks:
  - prepare: |
      sudo mkdir /data /opt/termux
      sudo chown $(id -u):$(id -u) /data /opt/termux
      sudo install -Dm755 ./termux-musl/scripts/fake-ldconfig.sh /usr/local/bin/ldconfig
  - install-toolchains: |
      curl --silent --fail --retry 3 -L -o toolchain.tar.bz2 https://termux-musl.ml/toolchains/toolchain-aarch64.tar.bz2
      tar xf toolchain.tar.bz2 -C /opt/termux && rm -f toolchain.tar.bz2
      curl --silent --fail --retry 3 -L -o toolchain.tar.bz2 https://termux-musl.ml/toolchains/toolchain-arm.tar.bz2
      tar xf toolchain.tar.bz2 -C /opt/termux && rm -f toolchain.tar.bz2
      curl --silent --fail --retry 3 -L -o toolchain.tar.bz2 https://termux-musl.ml/toolchains/toolchain-i686.tar.bz2
      tar xf toolchain.tar.bz2 -C /opt/termux && rm -f toolchain.tar.bz2
      curl --silent --fail --retry 3 -L -o toolchain.tar.bz2 https://termux-musl.ml/toolchains/toolchain-x86_64.tar.bz2
      tar xf toolchain.tar.bz2 -C /opt/termux && rm -f toolchain.tar.bz2
  - install-android-sdk: |
      curl --silent --fail --retry 3 -L -o sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
      unzip -q sdk.zip -d /opt/termux/android-sdk && rm -f sdk.zip
      bash ./termux-musl/scripts/setup-sdk.sh > /dev/null
  - process-last-commit: |
      cd termux-musl
      bash ./scripts/ci-process-last-commit.sh
